# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\face_anti.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JPEG(object):
    def setupUi(self, JPEG):
        JPEG.setObjectName("JPEG")
        JPEG.resize(1410, 853)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        JPEG.setFont(font)
        JPEG.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"setWordWrap: True")
        JPEG.setInputMethodHints(QtCore.Qt.ImhNone)
        JPEG.setDocumentMode(False)
        JPEG.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(JPEG)
        self.centralwidget.setObjectName("centralwidget")
        self.aft_frame = QtWidgets.QLabel(self.centralwidget)
        self.aft_frame.setGeometry(QtCore.QRect(580, 180, 471, 471))
        self.aft_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.aft_frame.setText("")
        self.aft_frame.setObjectName("aft_frame")
        self.pre_img = QtWidgets.QLabel(self.centralwidget)
        self.pre_img.setEnabled(True)
        self.pre_img.setGeometry(QtCore.QRect(50, 80, 471, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pre_img.setFont(font)
        self.pre_img.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pre_img.setAcceptDrops(False)
        self.pre_img.setToolTip("")
        self.pre_img.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_img.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"")
        self.pre_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pre_img.setFrameShadow(QtWidgets.QFrame.Plain)
        self.pre_img.setScaledContents(False)
        self.pre_img.setAlignment(QtCore.Qt.AlignCenter)
        self.pre_img.setObjectName("pre_img")
        self.aft_img = QtWidgets.QLabel(self.centralwidget)
        self.aft_img.setGeometry(QtCore.QRect(580, 80, 471, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.aft_img.setFont(font)
        self.aft_img.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"")
        self.aft_img.setAlignment(QtCore.Qt.AlignCenter)
        self.aft_img.setObjectName("aft_img")
        self.chooseImage = QtWidgets.QPushButton(self.centralwidget)
        self.chooseImage.setGeometry(QtCore.QRect(1160, 290, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.chooseImage.setFont(font)
        self.chooseImage.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.chooseImage.setObjectName("chooseImage")
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(1160, 400, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Reset.setFont(font)
        self.Reset.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"")
        self.Reset.setObjectName("Reset")
        self.author = QtWidgets.QLabel(self.centralwidget)
        self.author.setGeometry(QtCore.QRect(1140, 550, 231, 121))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.author.setFont(font)
        self.author.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: rgb(245, 82, 123);\n"
"")
        self.author.setAlignment(QtCore.Qt.AlignCenter)
        self.author.setWordWrap(True)
        self.author.setObjectName("author")
        self.pre_frame = QtWidgets.QLabel(self.centralwidget)
        self.pre_frame.setGeometry(QtCore.QRect(50, 180, 471, 471))
        self.pre_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pre_frame.setText("")
        self.pre_frame.setObjectName("pre_frame")
        self.aft_img_2 = QtWidgets.QLabel(self.centralwidget)
        self.aft_img_2.setGeometry(QtCore.QRect(1100, 0, 311, 861))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.aft_img_2.setFont(font)
        self.aft_img_2.setStyleSheet("background-color: rgb(0, 171, 0);")
        self.aft_img_2.setText("")
        self.aft_img_2.setAlignment(QtCore.Qt.AlignCenter)
        self.aft_img_2.setObjectName("aft_img_2")
        self.aft_img_2.raise_()
        self.aft_frame.raise_()
        self.pre_img.raise_()
        self.aft_img.raise_()
        self.chooseImage.raise_()
        self.Reset.raise_()
        self.author.raise_()
        self.pre_frame.raise_()
        JPEG.setCentralWidget(self.centralwidget)

        self.retranslateUi(JPEG)
        QtCore.QMetaObject.connectSlotsByName(JPEG)

    def retranslateUi(self, JPEG):
        _translate = QtCore.QCoreApplication.translate
        JPEG.setWindowTitle(_translate("JPEG", "IMAGE PROCESSING"))
        self.pre_img.setText(_translate("JPEG", "Image"))
        self.aft_img.setText(_translate("JPEG", "Result"))
        self.chooseImage.setText(_translate("JPEG", "Choose Image"))
        self.Reset.setText(_translate("JPEG", "RESET"))
        self.author.setText(_translate("JPEG", "Happy fun!!!                                            )( <3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JPEG = QtWidgets.QMainWindow()
    ui = Ui_JPEG()
    ui.setupUi(JPEG)
    JPEG.show()
    sys.exit(app.exec_())
